### ISSUE TITLE
Dashboard canvas does not appear after navigating from the System Administration screen

### ISSUE THREAD

**Issue by scott-tyskowski** [CentrifugeTech/BlueWave#78]
After logging in
 - from the options on the top right, click System Administration
 - From options again, click Create Dashboard
 -  The dashboard canvas does not appear
 - User has to refresh the page and click on Create Dashboard to get the canvas and options.

**Comment by swordysrepo** [comment]
The bug was due to "Create Dashboard" not being called to be shown, after being hidden while visiting a page that hides it from view. The fix was to show the "Create Dashboard" page when navigated to from another page. The bug was that this line of code that re-shows the "Create Dashboard" page was missing.

**Comment by swordysrepo** [comment]
this issue still persists while transitioning from "Create Dashboard" -> "Dashboard Home" -> "Create Dashboard"
